language: cpp
compiler:
  - gcc
install:
#- sudo apt-get install build-essential
- sudo apt-get install -qq libboost-all-dev
- sudo apt-get install -qq libmpfr-dev
- sudo apt-get install -qq cmake
- sudo apt-get install -qq libeigen3-dev
- sudo apt-get install make
- sudo apt-get install -qq curl
- sudo apt-get install -qq libgmp3-dev
- curl -O https://gforge.inria.fr/frs/download.php/file/34149/CGAL-4.5.tar.gz
- tar zxvf CGAL-4.5.tar.gz &> install.log
- cd CGAL-4.5
- cmake -DCMAKE_BUILD_TYPE=Release -DWITH_Eigen3=ON .
- make
- sudo make install &>> install.log
- cd ..
- git clone https://github.com/pranavkantgaur/googletest.git 
- cd googletest
- mkdir build
- cd build 
- cmake ../
- sudo make install &>> install.log
- cd ../../  
script: 
       - mkdir build
       - cd build  
       - cmake ../
       - make  
